service: graph-shopping-cart

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-shopping-cart-example

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    shoppingCart:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: seq
            AttributeType: N
          -
            AttributeName: context
            AttributeType: S
        KeySchema:
          -
            AttributeName: context
            KeyType: HASH
          -
            AttributeName: seq
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
      
functions:
  graphqlHandler:
    handler: handler.graphqlHandler
    events:
      - http:
          path: api/query
          method: post
          cors: true
  
  graphiqlHandler:
    handler: handler.graphiqlHandler
    events:
      - http:
          path: graphiql
          method: get

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

plugins:
  - serverless-dynamodb-local
  - serverless-offline